package tool;

import java.lang.reflect.Field;

import jakarta.persistence.TemporalType;

public class FieldInfo
{
    String name;
    String columnName;
    Class<?> type;
    boolean isKey = false;
    boolean isKeyAutoGenerated = false;
    boolean updatable = true;
    boolean insertable = true;
    boolean isGetBy = false;
    boolean isListBy = false;
    boolean isUpdateBy = false;
    boolean isDeleteBy = false;
    Field   fieldToUpdate;
    TemporalType tp = TemporalType.TIMESTAMP;
    
    String tableName;
}
